### PR TITLE
100 implement auth

### PR DESCRIPTION
**Pull request by chrisahardie**

### CODE REVIEW

**Comment by andrewpmk** [comment]
Can you please translate the "Login" button (do you need me to help with that?) so it doesn't look ugly since Login button is visible by non authenticated users. Don't worry about translating anything else in admin portal because it's only for admins. French translation is "Connexion", use Google Translate for other languages which is usually OK for one word strings.

**Comment by chrisahardie** [comment]
> Can you please translate the "Login" button (do you need me to help with that?) so it doesn't look ugly since Login button is visible by non authenticated users. Don't worry about translating anything else in admin portal because it's only for admins. French translation is "Connexion", use Google Translate for other languages which is usually OK for one word strings.

I've added the keys to the locale files, but have to step away for a bit. Created [this ticket](https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/issues/103) to track this work.

**Comment by andrewpmk** [comment]
> 
> 
> > Can you please translate the "Login" button (do you need me to help with that?) so it doesn't look ugly since Login button is visible by non authenticated users. Don't worry about translating anything else in admin portal because it's only for admins. French translation is "Connexion", use Google Translate for other languages which is usually OK for one word strings.
> 
> I've added the keys to the locale files, but have to step away for a bit. Created [this ticket](https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/issues/103) to track this work.

Should I do this after you merge this pull request? There's two pull requests open this one and the admin page one, presumably they will get merged together?

**Comment by chrisahardie** [comment]
> > > Can you please translate the "Login" button (do you need me to help with that?) so it doesn't look ugly since Login button is visible by non authenticated users. Don't worry about translating anything else in admin portal because it's only for admins. French translation is "Connexion", use Google Translate for other languages which is usually OK for one word strings.
> > 
> > 
> > I've added the keys to the locale files, but have to step away for a bit. Created [this ticket](https://github.com/Vaccine-Hunters-Canada/VaxFinder-Frontend/issues/103) to track this work.
> 
> Should I do this after you merge this pull request? There's two pull requests open this one and the admin page one, presumably they will get merged together?

You could do it after, or you could checkout this branch, update the locale files and push, then they would be included in this PR.

**Comment by andrewpmk** [comment]
Updated this branch with translation of "login". Also changed fallback language to "en" instead of "en-CA" because otherwise the login screen doesn't display the English translations if another translation selected because it's not translated into any other language. Please pull and merge conflicts.

**Review by ericherscovich — APPROVED** [review]

**Pull request merged**
